services:
   traefik:
     image: traefik:v3.0
     container_name: traefik
     command:
     # --- Activation de l'API et du Dashboard (NON SÉCURISÉ) ---
       - "--api.insecure=true"
       # --- Configuration du fournisseur Docker ---
       - "--providers.docker=true"
       - "--providers.docker.exposedbydefault=false"
       # --- Configuration des points d'entrée (ports d'écoute) ---
       - "--entrypoints.web.address=:80"
       - "--entrypoints.websecure.address=:443"
       - "--certificatesresolvers.le.acme.email=hamohand@gmail.com"
       - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
       - "--certificatesresolvers.le.acme.tlschallenge=true"
     labels:
       # --- DEFINITION GLOBALE DU MIDDLEWARE DE REDIRECTION
       # Crée un middleware nommé 'https-redirect' : Traefik est disponible pour tous les conteneurs
       # qui est un schéma de redirection de http vers https.
       - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
       - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

     ports:
       - "80:80"
       - "443:443"
       - "8080:8080"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       # --- AJOUT POUR LE SSL ---
       # On crée un volume pour que Traefik puisse sauvegarder les certificats obtenus
       - traefik-letsencrypt:/letsencrypt

     networks:
       - webproxy

networks:
  webproxy:
    external: true

 # --- AJOUT POUR LE SSL ---
 # On déclare le volume pour le stockage des certificats
volumes:
  traefik-letsencrypt:
